# Generated by Django 3.2.6 on 2021-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipe', '0002_review_review_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_id',
            new_name='recipe',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.ManyToManyField(to='myrecipe.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='myrecipe.WeeklyMenu'),
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredient_name',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredient_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
